name: Deploy to GitHub Pages and Reupload All Files to Aliyun OSS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 确保有足够的权限来推送到 GitHub Pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # 使用最新版本的 checkout 动作

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # 设置使用的 Node.js 版本

      - name: Install pnpm
        run: npm install -g pnpm  # 安装 pnpm 包管理器

      - name: Install dependencies
        run: pnpm install  # 使用 pnpm 安装项目依赖

      - name: Build
        run: pnpm build  # 构建项目，生成静态资源

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的令牌进行部署
          publish_dir: pages/dist  # 指定构建输出目录
          publish_branch: gh-pages  # 指定发布到的分支

      # 下载并设置 ossutil 工具
      - name: Setup ossutil
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.15/ossutil64
          chmod 755 ossutil64
         ./ossutil64 config -e ${{ secrets.ALIYUN_OSS_ENDPOINT}} -i ${{ secrets.ALIYUN_ACCESS_KEY_ID }} -k ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }} --output-dir=./

      # 删除原始数据文件
      - name: Remove all original files from Aliyun OSS
        run: |
          # 删除指定目录下的所有文件和文件夹（包括子目录）
          # 注意：这将彻底移除目标位置的所有内容，请谨慎使用
         ./ossutil64 rm -rf oss://${{ secrets.ALIYUN_OSS_BUCKET_DIR }}/

      # 上传所有新文件 to Aliyun OSS
      - name: Upload all new files to Aliyun OSS
        run: |
          # 将本地构建的文件递归复制到 OSS 存储桶中
         ./ossutil64 cp --recursive./pages/dist oss://${{ secrets.ALIYUN_OSS_BUCKET_DIR }}/

      # 安装阿里云 CLI 工具
      - name: Install Aliyun CLI
        run: |
          curl https://raw.githubusercontent.com/aliyun/aliyun-cli/master/scripts/install.sh | sh

      # 配置阿里云 CLI（使用存储在secrets中的密钥信息）
      - name: Configure Aliyun CLI
        run: |
          aliyuncli configure set --profile default --access-key-id ${{ secrets.ALIYUN_ACCESS_KEY_ID }} --access-key-secret ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }} --region cn-beijing

      # 刷新阿里云 CDN 缓存
      - name: Refresh Aliyun CDN Cache
        run: |
          aliyuncli cdn RefreshObjectCaches --region cn-beijing --ObjectType File --Force true --ObjectPath ${{ secrets.ALIYUN_CDN_DOMAIN }}
